name: CI

on:
  push:
    branches:
      - master
  pull_request: {}
  workflow_dispatch: {}

env:
  CARGO_TERM_COLOR: always
  FRB_MAIN_RUST_VERSION: 1.74.0
  FRB_MAIN_DART_VERSION: 3.2.0
  FRB_MAIN_FLUTTER_VERSION: 3.16.0

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test_dart_native:
    name: 'Test :: Dart :: Native'
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        image:
          - windows-2019
          - macos-11
          - ubuntu-20.04
        package:
          - my_dart_package

    steps:
      # setup
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
          architecture: x64

      # execute
      - run: |-
          set -euxo pipefail
          cd ${{ matrix.package }}
          dart pub global activate coverage
          dart pub get
          dart test --coverage=coverage
          format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.dart_tool/package_config.json

      # report
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.job }}--${{ matrix.image }}--${{ matrix.package }}--coverage
          path: ${{ matrix.package }}/coverage/

  # Why one separate codecov job: Otherwise, when some jobs upload artifact while some not,
  # the (partial) coverage will show up and be very low - which surely does not reflect actual coverage.
  misc_codecov:
    name: 'Misc :: Codecov'
    runs-on: ubuntu-latest
    # NOTE need to depend on *all* jobs that may generate codecov artifacts
    needs:
      - test_dart_native

    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: downloaded-artifacts/

      - run: tree downloaded-artifacts

      - uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          directory: downloaded-artifacts
          verbose: true
